// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN-5qTf_fh6hvOOqyJA-4Pi_lrP1-NPZg',
    appId: '1:16811379929:web:58d98dbd06447b5cbc02c8',
    messagingSenderId: '16811379929',
    projectId: 'homeauditapp-327d7',
    authDomain: 'homeauditapp-327d7.firebaseapp.com',
    storageBucket: 'homeauditapp-327d7.firebasestorage.app',
    measurementId: 'G-XGQ66R998T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwk_Mo8x59fSvlYnIfLWuQETDAE3sjw2w',
    appId: '1:16811379929:android:b02357d292f994e2bc02c8',
    messagingSenderId: '16811379929',
    projectId: 'homeauditapp-327d7',
    storageBucket: 'homeauditapp-327d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTlc84hkCCVdVSGOPiYXhqeELcVSTdA8g',
    appId: '1:16811379929:ios:0def7fa028bf31d7bc02c8',
    messagingSenderId: '16811379929',
    projectId: 'homeauditapp-327d7',
    storageBucket: 'homeauditapp-327d7.firebasestorage.app',
    iosBundleId: 'com.example.energyAuditApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTlc84hkCCVdVSGOPiYXhqeELcVSTdA8g',
    appId: '1:16811379929:ios:0def7fa028bf31d7bc02c8',
    messagingSenderId: '16811379929',
    projectId: 'homeauditapp-327d7',
    storageBucket: 'homeauditapp-327d7.firebasestorage.app',
    iosBundleId: 'com.example.energyAuditApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN-5qTf_fh6hvOOqyJA-4Pi_lrP1-NPZg',
    appId: '1:16811379929:web:6926da5136c3b8cebc02c8',
    messagingSenderId: '16811379929',
    projectId: 'homeauditapp-327d7',
    authDomain: 'homeauditapp-327d7.firebaseapp.com',
    storageBucket: 'homeauditapp-327d7.firebasestorage.app',
    measurementId: 'G-0GJFJCFERQ',
  );
}
